server:
  port: 8001
  
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true   #禁止配置中心的配置将客户端配置覆盖掉
    
eureka:
  instance:
    prefer-ip-address: true       # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式
    spring:
    